name = input("请输入姓名：")
time = input("当前学期：")
lv = input("请输入表现等级：")
print (" " * 5 + "奖状")
print(" ")
print("学生姓名：" + name)
print("学期：" + time)
print("表现等级：" + lv)
print(" ")
print("该生在本学期表现" + lv + "，特此颁奖以资鼓励。")
print(" ")
print("希望该生继续努力，取得更好成绩！")
import time
print("颁发日期：" + time.strftime('%y-%m-%d'))