name = input("请输入姓名：")
num = input("请输入学号：")
zy = input("请输入专业：")
xb = input("请输入学院：")
classname = input("请输入课程名称：")
cj = input("请输入成绩：")
print(" " * 8 + "广州应用科技学院")
print(" " * 10 + "课程成绩单")
print("姓名：" + name + " " * 12 + "学号：" + num)
print("专业：" + zy + " " * 8 + "系部：" + xb)
print("课程名称：" + classname + " " * 4 + "成绩：" + cj)